version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress

  maria-db:
    build: ./requirements/mariadb
    image: maria-db
    container_name: maria-db
    env_file:
      - .env
    restart: on-failure
    volumes:
      - maria_vol:/var/lib/mysql
    networks:
      - inception_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure
    volumes:
      - wp_vol
    networks:
      - inception_net
    depends_on:
      maria-db:
        condition: service_healthy

volumes:
  maria_vol:
    name: maria_vol
    driver_opts:
      type: none
      device: /home/nvideira/data/mysql
  wp_vol:
    name: wp_vol
    driver_opts:
      type: none
      device: /home/nvideira/data/wordpress

networks:
  inception_net:
    driver: bridge